.Dd Jun 7, 2018
.Dt SEARCHFS 1
.Os Darwin
.Sh NAME
.Nm searchfs
.Nd fast filename search on HFS+ and APFS volumes
.Sh SYNOPSIS
.Nm
.Op Fl dfeh
.Op Fl v Ar mount_point
.Ar search_term
.Sh DESCRIPTION
.Nm
does filename search on HFS+ and APFS volumes. Searching takes place
at the driver level using the file system catalog via the low-level
searchfs() function. This means the volume's entire directory tree can
be scanned much faster than with a standard recursive directory search.
.Pp
Paths of files with names containing search_term are printed to STDOUT, one
path per line. Only case-insensitive search is supported at this time due to
limitations in the low-level Darwin API.
.Pp
The following flags are supported:
.Bl -tag -width -indent
.It Fl v, -volume
Specify volume to search. Default is the root file system at /
.It Fl d, -dirs-only
Return only matching directories
.It Fl f, -files-only
Return only matching files
.It Fl e, -exact-match-only
Return only exact filename matches
.It Fl h, -help
Print usage and exit
.El
.Sh SEE ALSO
.Xr find 1 ,
.Xr locate 1 ,
.Xr mdfind 1 ,
.Xr searchfs 2
.Sh AUTHORS
.An Sveinbjorn Thordarson <sveinbjorn@sveinbjorn.org>
