.Dd May 16, 2019
.Dt SEARCHFS 1
.Os Darwin
.Sh NAME
.Nm searchfs
.Nd fast filename search on HFS+ and APFS volumes
.Sh SYNOPSIS
.Nm
.Op Fl ldfespixnmoh
.Op Fl v Ar mount_point/device_namelist_volumes
.Ar search_term
.Sh DESCRIPTION
.Nm
searches for files by name on APFS and HFS+ volumes. Searching takes place at
the driver level using the file system catalog via the low-level searchfs()
kernel call. This means the volume's entire directory tree can be scanned much
faster than with a standard recursive directory search using /usr/bin/find.
.Pp
The paths to all files and directories with names matching the search term are
printed to the standard output, one path per line. Search is case-insensitive by
default.
.Pp
The following flags are supported:
.Bl -tag -width -indent
.It Fl l, -list
List all mounted filesystems that support catalog search.
.It Fl v, -volume Ar path
Specify volume to search, either by mount path (e.g. "/Volumes/SomeVol") or
device name (e.g. "/dev/disk2s1"). Default is the root file system
mounted at /.
.It Fl d, -dirs-only
Match directories only.
.It Fl f, -files-only
Match files only.
.It Fl e, -exact-match
Exact filename matches only.
.It Fl s, -case-sensitive
Case sensitive matching.
.It Fl p, -skip-packages
Don't match file system objects that are inside a package. A package is
defined as a directory whose extension matches one of the extensions that
are configured into the kernel by Launch Services.
.It Fl i, -skip-invisibles
Don't match invisible file system objects (that is, objects with the
Finder attribute "Invisible" set) or any objects within invisible directories.
.It Fl x, -skip-inappropriate
Don't match any file system objects that are within an "inappropriate" directory.
Apple's current list of inappropriate directories contains one item: /System.
.It Fl n, -negate-params
Show all file system objects that do *not* match the search term.
.It Fl m, -limit Ar number
Terminate when the specified number of matching items has been found.
.It Fl o, -version
Print program version and exit.
.It Fl h, -help
Print usage and exit.
.El
.Sh EXAMPLES
Find directories with name matching 'something' on root volume:
.Pp
.Dl searchfs -d "something"
.Pp
Find file with the exact name 'file.txt' on volume 'SomeHD':
.Pp
.Dl searchfs -v "/Volumes/SomeHD" -e "file.txt"
.Pp
The regular expression characters ^ and $ can be used to match only the
beginning or only the end of a string, respectively.
.Pp
For example, find all filenames ending with the suffix '.txt':
.Pp
.Dl searchfs '.txt$'
.Pp
Find all filenames starting with "CHANGES":
.Pp
.Dl searchfs -s "^CHANGES"
.Pp
Find *all* files on the root filesystem:
.Pp
.Dl searchfs *
.Sh SEE ALSO
.Xr find 1 ,
.Xr locate 1 ,
.Xr mdfind 1 ,
.Xr searchfs 2
.Sh AUTHORS
.An Sveinbjorn Thordarson <sveinbjorn@sveinbjorn.org>
